import os
print('Installing Lutris')
os.system("sudo add-apt-repository ppa:lutris-team/lutris")
os.system("sudo apt-get update")
os.system("sudo apt-get install lutris")
print('Installing kdenlive')
os.system("sudo apt-get install kdenlive")
print('Installing Steam')
os.system("sudo apt install steam-installer")
print('Installing Discord')
os.system("sudo apt-get install snapd")
os.system("sudo snap install discord")
print("Installing OBS")
os.system("sudo add-apt-repository ppa:obsproject/obs-studio")
os.system("sudo apt update")
os.system("sudo apt install obs-studio")
print("installed everything!")
print('WINE is good to install too!')
